version: '3'
services:
  cloudcanal:
    image: ghcr.io/shiny/cloudcanalclient:saas-20221027
    volumes:
      - ./conf.properties:/home/cloudcanal/cloudcanal/global_conf/conf.properties
      - ./logs:/home/cloudcanal/logs
    restart: unless-stopped
